FROM node:22-alpine

WORKDIR /app

# Установка зависимостей (включая devDependencies для dev контейнера)
COPY package.json package-lock.json* ./
RUN npm ci --include=dev

# Копирование остальных файлов
COPY . .

# Генерация Prisma Client
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
